set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim

call plug#begin()
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
Plug 'ncm2/ncm2-bufword'
Plug 'ncm2/ncm2-path'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'Shougo/deoplete.nvim'
Plug 'roxma/nvim-yarp'
Plug 'dense-analysis/ale'
Plug 'roxma/vim-hug-neovim-rpc'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

" Fuzzy Finder
Plug 'airblade/vim-rooter'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
call plug#end()

" Auto Completion Configuration
autocmd BufEnter * call ncm2#enable_for_buffer()
set completeopt=noinsert,menuone,noselect

let g:deoplete#enable_at_startup = 1

call vundle#begin()
Plugin 'vim-plug'
Plugin 'VundleVim/Vundle.vim'
Plugin 'hashivim/vim-terraform'
Plugin 'Yggdroot/indentLine'
call vundle#end()

syntax enable
syntax on
filetype plugin indent on
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab


inoremap ii <Esc>
inoremap " ""<left>
inoremap ' ''<left>
inoremap ( ()<left>
inoremap [ []<left>
inoremap { {}<left>
inoremap {<CR> {<CR>}<ESC>O
inoremap (<CR> (<CR>)<ESC>O
inoremap {;<CR> {<CR>};<ESC>O

inoremap <expr><Tab> (pumvisible()?(empty(v:completed_item)?"\<C-n>":"\<C-y>"):"\<Tab>")


set number
set showcmd
set ruler
set backspace=indent,eol,start
set incsearch
set ignorecase
set hlsearch

" Search the trailing whitespaces with '/\s\+$'
highlight RedundantSpaces ctermbg=red guibg=red
match RedundantSpaces /\s\+$/

" Check Spelling with Specific Language
" set spell spelllang=en_us

set nocursorline
" set textwidth=80

" Avoid relative number for cursor.
set norelativenumber

" Indentation

set autoindent
set smartindent
set complete-=1
set showmatch
set smarttab
set tabstop=4
set shiftwidth=4
set expandtab

" Persistent undo
" set undofile
" set undodir=~/.vim/undodir

" This allows to yank contents to another file.
set clipboard=unnamedplus

" For groovy syntax.
au BufNewFile,BufRead Jenkinsfile setf groovy

" YAML syntax
" https://github.com/chase/vim-ansible-yaml
Bundle 'chase/vim-ansible-yaml'
let g:indentLine_char = '┊'
