icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "net"
device = "wlp9s0"
interval = 3

[[block]]
block = "net"
device = "wlp9s0"
format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device "

[[block]]
block = "net"
device = "enp0s31f6"
interval = 3

[[block]]
block = "net"
device = "enp0s31f6"
format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device "

#[[block]]
#block = "speedtest"
#interval = 3
#format = " ^icon_ping $ping "
#
#[[block]]
#block = "speedtest"
#interval = 3
#format = " $speed_down $speed_up"

