icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome4"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $available / $total "

#[[block]]
#block = "weather"
#format = "{weather} ({location}) {temp}, {wind} m/s {direction}"
#service = { name = "openweathermap", api_key = "XXXXXXXXXXXXXXX", city_id = "1283240", units = "metric" }
#
#[[block]]
#block = "xrandr"
#icons = true
#resolution = true
#interval = 2

#[[block]]
#block = "temperature"
#collapsed = false
#interval = 10
#format = "{min} min, {max} max, {average} avg"
#chip = "*-isa-*"

#[[block]]
#block = "speedtest"
#interval = 3

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:Mi)/$swap_total.eng(w:3,u:B,p:Mi)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

#[[block]]
#block = "custom"
#command = "echo '\uf0ac ' `curl bot.whatismyipaddress.com`" # assumes fontawesome icons
#interval = 60

[[block]]
block = "load"
format = " $icon 1min avg: $1m.eng(w:4) "
interval = 1

#[[block]]
#block = "music"
#player = "spotify"
#buttons = ["play", "next"]

#[[block]]
#block = "custom"
#command = "echo \uf011" # assumes fontawesome icons
#on_click = "systemctl `echo -e 'suspend\npoweroff\nreboot' | dmenu`"
#interval = "once"

#[[block]]
#block = "custom"
#command = "xrandr --listmonitors | tail -n+2 | tr '+' ' ' | cut -d' ' -f 4 | tr '\n' ' '"
#interval = "once"
#signal = 4

#[[block]]
#block = "maildir"
#interval = 60
#inboxes = ["/home/omega/mail/local","/home/omega/Mail", "/home/omega/mail/gmail/Inbox"]
#threshold_warning = 1
#threshold_critical = 10
#display_type = "new"

#[[block]]
#block = "github"
#format = "{total}|{author}|{comment}|{mention}|{review_requested}"

[[block]]
block = "docker"
interval = 2
format = " $icon $running/$total "

#[[block]]
#block = "net"
#device = "wlp9s0"
#interval = 3

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization "
format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "custom"
command = "uname -r"

[[block]]
block = "custom"
command = "cat /etc/fedora-release | awk '{print $1 $3}'"

[[block]]
block = "uptime"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "battery"
missing_format = ""

[[block]]
block = "time"
interval = 60
[block.format]
short = " $icon $timestamp.datetime(f:%R) "


## Network Configuration

#[[block]]
#block = "net"
#device = "wlp9s0"
#interval = 3
#
#[[block]]
#block = "net"
#device = "wlp9s0"
#format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device "
#
#[[block]]
#block = "net"
#device = "enp0s31f6"
#interval = 3
#
#[[block]]
#block = "net"
#device = "enp0s31f6"
#format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device "

