#!/bin/bash
set -e

xrandr --output DP-3 --auto
xrandr --output DP-2 --auto

xrandr --output DP-3 --auto --left-of eDP-1
xrandr --output DP-3 --auto --left-of DP-2
xrandr --output DP-3 --rotate left
xrandr --output DP-2 --auto --above eDP-1

i3-msg "workspace 1, move workspace to output eDP-1"
i3-msg "workspace 2, move workspace to output eDP-1"
i3-msg "workspace 3, move workspace to output eDP-1"


i3-msg "workspace 4, move workspace to output DP-3"
i3-msg "workspace 5, move workspace to output DP-3"
i3-msg "workspace 6, move workspace to output DP-3"

i3-msg "workspace 7, move workspace to output DP-2"
i3-msg "workspace 8, move workspace to output DP-2"
i3-msg "workspace 9, move workspace to output DP-2"
