#!/bin/bash

# Only exported variables can be used within the timer's command.
export PRIMARY_DISPLAY="$(xrandr | awk '/ primary/{print $1}')"

# Run xidlehook
xidlehook \
  `# Don't lock when there's a fullscreen application` \
  --not-when-fullscreen \
  `# Don't lock when there's audio playing` \
  --not-when-audio \
  `# Dim the screen after 120 seconds, undim if user becomes active` \
  --timer 120 \
    'xrandr --output "$PRIMARY_DISPLAY" --brightness .1' \
    'xrandr --output "$PRIMARY_DISPLAY" --brightness 1' \
  `# Undim & lock after 5 more seconds` \
  --timer 5 \
    'xrandr --output "$PRIMARY_DISPLAY" --brightness 1; i3lock -i /home/omega/.config/i3/wall/fedora.png -t -ef -n' \
    '' \
  `# Finally, suspend after 120 Seconds` \
  --timer 120 \
    'systemctl suspend' \
    ''
