#!/bin/bash
# Open the specific program in dedicated workspace
i3-msg 'workspace 1; exec alacritty'
sleep 1
i3-msg 'workspace 2; exec google-chrome'
sleep 1
#exec --no-startup-id i3-msg 'workspace 2; exec google-chrome'
i3-msg 'workspace 5; exec /usr/bin/gnome-terminal -- zsh -c 'mutt''
i3-msg 'workspace 6; exec /usr/bin/gnome-terminal -- zsh -c 'weechat''
i3-msg 'workspace 7; exec /usr/bin/firefox'
sleep 1
