import = [ "~/.config/alacritty/colors.yml", "~/.config/alacritty/fonts.yml" ]

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = '1.0'

[window]
dimensions = { columns = 82, lines = 24 }
position = { x = 0, y = 0 }
padding = { x = 0, y = 0 }
opacity = 1.0
decorations = "Full"
startup_mode = "Windowed"
dynamic_title = true

[scrolling]
history = 5000

[cursor]
style = {shape = "Beam", blinking = "On"}
thickness = 0.15
unfocused_hollow = false

[shell]
program = "/bin/zsh"
